name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: fireflyframework/.github/.github/workflows/go-release.yml@main
    with:
      go-version: '1.25'
      binary-name: flywork
    permissions:
      contents: write
